<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title","Персонал");
$APPLICATION->SetPageProperty("description","Персонал");
$APPLICATION->SetTitle("Персонал");
$APPLICATION->SetPageProperty("HIDE_LEFT_BLOCK", "Y");
?>
<?$APPLICATION->IncludeComponent("bitrix:news", "doctors", array(
	"IBLOCK_TYPE" => "doctors",
	"IBLOCK_ID" => "#DOCTORS_IBLOCK_ID#",
	"REVIEWS_DOCTORS_IBLOCK_ID" => "#REVIEWS_DOCTORS_IBLOCK_ID#",
	"SERVICES_IBLOCK_ID" => "#SERVICES_IBLOCK_ID#",
	"TEMPLATE_THEME" => "site",
	"NEWS_COUNT" => "10",
	"USE_SEARCH" => "N",
	"USE_RSS" => "Y",
	"NUM_NEWS" => "20",
	"NUM_DAYS" => "180",
	"YANDEX" => "N",
	"USE_RATING" => "N",
	"USE_CATEGORIES" => "N",
	"USE_REVIEW" => "N",
	"USE_FILTER" => "N",
	"SORT_BY1" => "ACTIVE_FROM",
	"SORT_ORDER1" => "DESC",
	"SORT_BY2" => "SORT",
	"SORT_ORDER2" => "ASC",
	"CHECK_DATES" => "Y",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "#SITE_DIR#doctors/",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_SHADOW" => "Y",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "Y",
	"AJAX_OPTION_HISTORY" => "N",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "36000000",
	"CACHE_FILTER" => "N",
	"CACHE_GROUPS" => "Y",
	"DISPLAY_PANEL" => "Y",
	"SET_TITLE" => "Y",
	"SET_STATUS_404" => "Y",
	"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
	"ADD_SECTIONS_CHAIN" => "Y",
	"ADD_ELEMENT_CHAIN" => "Y",
	"USE_PERMISSIONS" => "N",
	"PREVIEW_TRUNCATE_LEN" => "",
	"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
	"LIST_FIELD_CODE" => array(
		0 => "",
		1 => "",
	),
	"LIST_PROPERTY_CODE" => array(
		0 => "",
		1 => "",
	),
	"HIDE_LINK_WHEN_NO_DETAIL" => "N",
	"DISPLAY_NAME" => "Y",
	"META_KEYWORDS" => "",
	"META_DESCRIPTION" => "Y",
	"BROWSER_TITLE" => "Y",
	"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
    "IBLOCK_URL" => "#SITE_DIR#doctors/",
	"DETAIL_FIELD_CODE" => array(
		0 => "",
		1 => "",
	),
	"DETAIL_PROPERTY_CODE" => array(
		0 => "SPECIALIZATION",
		1 => "EXPERIENCE",
		2 => "PHONE",
		3 => "EMAIL",
		4 => "INSTAGRAM",
		5 => "FACEBOOK",
		6 => "WHATSAPP",
		7 => "VK",
		8 => "TELEGRAM",
		9 => "SERTIFICATS",
		10 => "REVIEWS",
		11 => "MORE_PHOTO",
	),
	"DETAIL_DISPLAY_TOP_PAGER" => "N",
	"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
	"DETAIL_PAGER_TITLE" => "Страница",
	"DETAIL_PAGER_TEMPLATE" => "arrows",
	"DETAIL_PAGER_SHOW_ALL" => "Y",
	"DISPLAY_TOP_PAGER" => "N",
	"DISPLAY_BOTTOM_PAGER" => "Y",
	"PAGER_TITLE" => "Новости",
	"PAGER_SHOW_ALWAYS" => "N",
	"PAGER_TEMPLATE" => "arrows",
	"PAGER_DESC_NUMBERING" => "N",
	"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
	"PAGER_SHOW_ALL" => "N",
	"DISPLAY_DATE" => "Y",
	"DISPLAY_PICTURE" => "Y",
	"DISPLAY_PREVIEW_TEXT" => "Y",
	"AJAX_OPTION_ADDITIONAL" => "",
	"SLIDER_PROPERTY" => "PICS_NEWS",
	"SEF_URL_TEMPLATES" => array(
		"news" => "",
		"section" => "#SECTION_CODE_PATH#/",
		"detail" => "#ELEMENT_CODE#/",
		"search" => "search/",
		"rss" => "rss/",
		"rss_section" => "#SECTION_ID#/rss/",
	),
    "SEND_REVIEWS" => "Y",
    "SHOW_REVIEWS" => "Y",
    "SHOW_SECTIONS" => "Y",
	),
	false
);?>

<?/*<div id="main_page_form" class="no_margin through_form">
    <?$APPLICATION->IncludeFile('/include/through_form.php');?>
</div>*/?>

<?
$APPLICATION->SetPageProperty("HIDE_LEFT_BLOCK", "Y");
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>